version: '2'

services:
  kcptun-client-main:
    container_name: kcptun-client
    image: lisnaz/kcptun-client:latest
    ports:
     - "8388:8388/tcp"
    networks:
      default:
        ipv4_address: 172.18.0.2
    environment:
      - KCPTUN_CLIENT_LISTEN_ADDR=<your kcptun client's listening address>
      - KCPTUN_CLIENT_LISTEN_PORT=<your kcptun client's listening port>
      - KCPTUN_CLIENT_TARGET_ADDR=<your kcptun server's address>
      - KCPTUN_CLIENT_TARGET_PORT=<your kcptun server's port>
      - KCPTUN_CRYPT=none
      - KCPTUN_MODE=fast2
      - KCPTUN_RCVWND=1024
      - KCPTUN_MTU=1400
      - KCPTUN_NOCOMP=false

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
